### ISSUE TITLE
Does Microsoft’s Edge support log styles?

### ISSUE THREAD

**Issue by gr2m** [gr2m/browser-supports-log-styles#23]
I don’t have Windows myself but would love if someone could test it for me.

Run this in Edge’s browser console: 

```js
console.log('%cLOG%c styling supported', 'color: white; padding: .2em .5em; border-radius: 1em; background-color: blue', 'color: inherit')
```

The result should look sth like this:

<img width="524" alt="screen shot 2017-02-19 at 09 38 59" src="https://cloud.githubusercontent.com/assets/39992/23104671/42ac3f48-f687-11e6-9e2c-78261dbef26b.png">

If it does, check if `browserSupportsLogStyles()` returns true:

1. Copy the content of [the built version of browser-supports-log-styles
](https://wzrd.in/standalone/browser-supports-log-styles) and paste it in the browser console
2. run `browserSupportsLogStyles()`

Thanks for your help <3

**Comment by coderbyheart** [comment]
![console](https://cloud.githubusercontent.com/assets/188915/23104725/802da4b4-f6d3-11e6-8a78-4fb3b0212055.PNG)

**Comment by nolanlawson** [comment]
No, not right now:

![screenshot 2017-02-19 09 44 03](https://cloud.githubusercontent.com/assets/283842/23104719/fda866aa-f687-11e6-96c0-d59030c7988c.png)

We do have a lot of plans to improve the F12 tools, though. :smiley: So maybe in a future release.

**Comment by coderbyheart** [comment]
P.S. you can test in edge via BrowserStack for free.

**Comment by gr2m** [comment]
Thanks you two! I’ll put in a regular reminder to check it again :)

**Comment by nolanlawson** [comment]
Yes you can also run it locally using VMs from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and VirtualBox. :)

**Comment by gr2m** [comment]
@coderbyheart @nolanlawson could one of you check with the latest version?

@nolanlawson is there a bug or sth I can track for styling support in edge?

**Comment by nolanlawson** [comment]
Try checking the Windows Insider build; I know the console and DOM explorer
are the first two parts of F12 that are getting a makeover.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson
