### ISSUE TITLE
Remove dist/ from npm package

### ISSUE THREAD

**Issue by ai** [gr2m/browser-supports-log-styles#24]
Thanks for awesome tool. I used it in my new project.

But why npm package contains `dist/` directory. If ypou use npm, you must to use some bundler like `webpack` or `browserify`.

`node_modules` size is a big problem of frontend community right now. I think it should be cool to try to keep it as small as possible.

**Comment by gr2m** [comment]
The `dist/` folder is for folks who don’t use build tools. 

> If ypou use npm, you must to use some bundler like webpack or browserify.

that is not true, yo ucan simply npm install and then load the file directly from `node_modules/browser-supports-log-styles/dist`. It’s the most accessible way for beginners and I don’t want to remove that
